---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 4
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 80
---
